### ISSUE TITLE
Missing file data_info.json

### ISSUE THREAD

**Issue by pimatysiak** [jadie1/BVIB-DeepSSM#1]
Hi there, thank you for making your code available.

However when trying to run the evaluation part after training a model, I am met with an error as it requires access to a file named data_info.json, which is hard-coded into the evaluation script, but does not seem to be part of the original dataset nor is it something that is generated by the SS_loaders script, or the training script.

Could you please provide guidance as to what steps are necessary to generate or obtain this file? 

Thank you

**Comment by jadie1** [comment]
Thank you for the note. I've added the data_info.json file to the SS_data folder.
